### PR TITLE
rsid_list is not optional

### PR DESCRIPTION
**Pull request by masterskipper**
## Description
 RSID List is not optional. 

API Response tells -

```
{
    "error": "Bad Request",
    "error_description": "rsid_list is a required array of report suites.",
    "error_uri": null
}
```

If you skip that option.

## Motivation and Context

Betterment of Docs

## Screenshots (if appropriate):
image

## Types of changes
Documentation

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by masterskipper** [comment]
@stevja1 @mike2184  hey guys! could you take a look?

**Comment by nateprice7** [comment]
@masterskipper - This change looks good to me. Our process won't let us merge the change in until the CLA is signed. Would you be able to do that?

**Comment by masterskipper** [comment]
merge is a go 👍

**Comment by stevja1** [comment]
Thanks @masterskipper !

**Pull request merged**
